[general]
resource_parser_url = https://cdn.jsdelivr.net/gh/xszo/etc@etc/network/quantumult-parser.js
network_check_url = http://1.1.1.1/
server_check_url = http://1.1.1.1/

[dns]
server = 223.5.5.5
server = 223.6.6.6
doh-server = https://223.5.5.5/dns-query, https://223.6.6.6/dns-query

[mitm]

[policy]
url-latency-benchmark = JP, server-tag-regex=(?<![A-Za-z])JPN?(?![A-Za-z])|Japan|Japanese|Tokyo|Osaka|日本國?|(?<!尼)日(?![\u4E00-\u9FFF])
url-latency-benchmark = TW, server-tag-regex=(?<![A-Za-z])TWN?(?![A-Za-z])|Taiwan|Taiwanese|Taipei|台灣|台湾|台(?![\u4E00-\u9FFF])
url-latency-benchmark = US, server-tag-regex=(?<![A-Za-z])(?:USA?|NY|LA)(?![A-Za-z])|United\s?States|American?|美國|美国|美(?![\u4E00-\u9FFF])

[filter_local]
final, TW

[filter_remote]
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+world.txt, tag=DNworld, force-policy=TW, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+cn.txt, tag=DNcn, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+jp.txt, tag=DNjp, force-policy=JP, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+tw.txt, tag=DNtw, force-policy=TW, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+us.txt, tag=DNus, force-policy=US, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+world.txt, tag=IPworld, force-policy=TW, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+cn.txt, tag=IPcn, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+jp.txt, tag=IPjp, force-policy=JP, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+tw.txt, tag=IPtw, force-policy=TW, update-interval=86400, opt-parser=true, enabled=true

[rewrite_local]

[rewrite_remote]

[server_local]

[server_remote]
